// This file is auto-generated by scripts/genBuildInfo.mjs. Do not edit.
export const COMMIT_HASH = 'c05df06';
export const COMMIT_DATE = '2025-10-17T19:30:33+02:00';
export const COMMIT_SUBJECT = 'update api/sendEmail.ts';
