// This file is auto-generated by scripts/genBuildInfo.mjs. Do not edit.
export const COMMIT_HASH = 'a5eb4c8';
export const COMMIT_DATE = '2025-12-18T20:31:56+01:00';
export const COMMIT_SUBJECT = 'modify color h1 h2';
